#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'


require 'csv'
require "pathname"
require "http"

data = []

#this is a comment

path = Pathname.new("Message.csv")
puts "Hola !"
csv_text = File.read(path)
csv = CSV.parse(csv_text, :headers => true)
csv.each do |row|
  data << {mob: row[0], name: row[1], account: row[2]}
end

path = Pathname.new("body.txt")
text = File.read(path)


puts "Where shell we start from ?"
sms_start = gets.chomp.to_i

puts "Enter total number of sms you want to send"
total_sms = gets.chomp.to_i

puts "How many SMS you want to send in a minute"
sms_pm = gets.chomp.to_i

sms_start = sms_start - 1


sms_end = sms_start + total_sms


puts "SMS start: #{sms_start}"
puts "SMS end: #{sms_end}"



if sms_end > data.size
  puts "Invalid! , number of records is less"
  exit!
end


puts "SMS start: #{sms_start}"
puts "SMS end: #{sms_end}"


data[sms_start..sms_end].each_slice(sms_pm) do |slice|
  slice.each do |row|
    msg = %(
Dear #{row[:name]},
Account # #{row[:account]}
#{text}
)

  Thread.new do
    h = HTTP.post("https://api.zipwhip.com/messaging/send",
    form: {session: "25655890-fa2e-4c0a-a60c-44ae477625be:343254802", to: "1#{row[:mob]}", body: msg} )

    puts "Sms sent to #{row[:mob]}, status: #{eval(h.body.to_s)[:success]}"
  end

  end
  sleep(1*60)
end
